/* This file was generated by syncqt. */
#ifndef QT_QTTEST_VERSION_H
#define QT_QTTEST_VERSION_H

#define QTTEST_VERSION_STR "5.2.1"

#define QTTEST_VERSION 0x050201

#endif // QT_QTTEST_VERSION_H
