@echo off
cd bin
copy C:\WINDOWS\system32\msvcp100.dll
copy C:\WINDOWS\system32\msvcr100.dll
copy C:\WINDOWS\system32\rtl60.bpl
copy C:\WINDOWS\system32\vcl60.bpl
copy C:\WINDOWS\system32\vclx60.bpl
copy C:\WINDOWS\system32\dbrtl60.bpl
copy C:\WINDOWS\system32\vcldb60.bpl
copy C:\PROGRAM\Borland\CBuilder6\Bin\bcbie60.bpl
copy C:\PROGRAM\Borland\CBuilder6\Bin\borlndmm.dll
copy C:\PROGRAM\Borland\CBuilder6\Bin\cc3260mt.dll
copy C:\PROGRAM\Borland\CBuilder6\Bin\ThemeManagerC6.bpl
copy C:\PROGRAM\Borland\CBuilder6\Bin\VirtualTreesC6.bpl
copy D:\PRJ\CrHack\bin\vc2010_win32_x86\CrH_CORE.dll
copy D:\PRJ\CrHack\bin\vc2010_win32_x86\CrH_BLIT.dll
copy D:\PRJ\CrHack\bin\vc2010_win32_x86\CrH_COMM.dll
copy D:\PRJ\CrHack\bin\vc2010_win32_x86\CrH_EXTZ.dll
copy D:\PRJ\FinalBIN\FreeImage\lib\win32_vc09_x86\FreeImage.dll
copy D:\PRJ\FinalBIN\DevIL\lib\win32_vc08_x86\unicode\DevIL.dll
copy D:\PRJ\FinalBIN\FMODEx\lib\mswin\fmodex.dll
copy D:\PRJ\FinalBIN\UnRAR\lib\win32_vc09_x86\unrar.dll
copy D:\PRJ\FinalBIN\Scintilla\lib\win32_vc10_x86\SciLexer.dll
copy D:\LIB\opencv\build\x86\vc10\bin\opencv_core244.dll
copy D:\LIB\opencv\build\x86\vc10\bin\opencv_highgui244.dll
copy D:\LIB\opencv\build\x86\vc10\bin\opencv_imgproc244.dll
