@echo off
rem =====================
call "%VS100COMNTOOLS%vsvars32.bat"
rem =====================
nmake -fgfx2.mak
rem =====================
nmake -fgdiwin.mak
rem =====================
nmake -fdx8win.mak
rem =====================
nmake -fdx9win.mak
rem =====================
