/* This file was generated by syncqt. */
#ifndef QT_QTHELP_VERSION_H
#define QT_QTHELP_VERSION_H

#define QTHELP_VERSION_STR "5.2.1"

#define QTHELP_VERSION 0x050201

#endif // QT_QTHELP_VERSION_H
