# Define SciTE settings for Escape Sequence files.


file.patterns.escseq=*.ans

filter.escseq=Escape Sequence (ans)|$(file.patterns.escseq)|

*filter.escseq=$(filter.escseq)

lexer.$(file.patterns.escseq)=escseq

*language.escseq=&Escape Sequence|ans||

# Properties styles

colour.escseq_fore_default=fore:#000000
colour.escseq_fore_black=fore:#767676
colour.escseq_fore_red=fore:#E74856
colour.escseq_fore_green=fore:#16C60C
colour.escseq_fore_yellow=fore:#F9F1A5
colour.escseq_fore_blue=fore:#3B78FF
colour.escseq_fore_magenta=fore:#B4009E
colour.escseq_fore_cyan=fore:#61D6D6
colour.escseq_fore_white=fore:#F2F2F2

colour.escseq_back_default=back:#FFFFFF
colour.escseq_back_black=back:#0C0C0C
colour.escseq_back_red=back:#C50F1F
colour.escseq_back_green=back:#13A10E
colour.escseq_back_yellow=back:#C19C00
colour.escseq_back_blue=back:#0037DA
colour.escseq_back_magenta=back:#881798
colour.escseq_back_cyan=back:#3A96DD
colour.escseq_back_white=back:#CCCCCC

# 0  DEFAULT
style.escseq.0=$(colour.escseq_fore_default),$(colour.escseq_back_default)
# 1  BLACK_DEFAULT
style.escseq.1=$(colour.escseq_fore_black),$(colour.escseq_back_default)
# 2  RED_DEFAULT
style.escseq.2=$(colour.escseq_fore_red),$(colour.escseq_back_default)
# 3  GREEN_DEFAULT
style.escseq.3=$(colour.escseq_fore_green),$(colour.escseq_back_default)
# 4  YELLOW_DEFAULT
style.escseq.4=$(colour.escseq_fore_yellow),$(colour.escseq_back_default)
# 5  BLUE_DEFAULT
style.escseq.5=$(colour.escseq_fore_blue),$(colour.escseq_back_default)
# 6  MAGENTA_DEFAULT
style.escseq.6=$(colour.escseq_fore_magenta),$(colour.escseq_back_default)
# 7  CYAN_DEFAULT
style.escseq.7=$(colour.escseq_fore_cyan),$(colour.escseq_back_default)
# 8  WHITE_DEFAULT
style.escseq.8=$(colour.escseq_fore_white),$(colour.escseq_back_default)
# 9  DEFAULT_BLACK
style.escseq.9=$(colour.escseq_fore_default),$(colour.escseq_back_black)
# 10  BLACK_BLACK
style.escseq.10=$(colour.escseq_fore_black),$(colour.escseq_back_black)
# 11  RED_BLACK
style.escseq.11=$(colour.escseq_fore_red),$(colour.escseq_back_black)
# 12  GREEN_BLACK
style.escseq.12=$(colour.escseq_fore_green),$(colour.escseq_back_black)
# 13  YELLOW_BLACK
style.escseq.13=$(colour.escseq_fore_yellow),$(colour.escseq_back_black)
# 14  BLUE_BLACK
style.escseq.14=$(colour.escseq_fore_blue),$(colour.escseq_back_black)
# 15  MAGENTA_BLACK
style.escseq.15=$(colour.escseq_fore_magenta),$(colour.escseq_back_black)
# 16  CYAN_BLACK
style.escseq.16=$(colour.escseq_fore_cyan),$(colour.escseq_back_black)
# 17  WHITE_BLACK
style.escseq.17=$(colour.escseq_fore_white),$(colour.escseq_back_black)
# 18  DEFAULT_RED
style.escseq.18=$(colour.escseq_fore_default),$(colour.escseq_back_red)
# 19  BLACK_RED
style.escseq.19=$(colour.escseq_fore_black),$(colour.escseq_back_red)
# 20  RED_RED
style.escseq.20=$(colour.escseq_fore_red),$(colour.escseq_back_red)
# 21  GREEN_RED
style.escseq.21=$(colour.escseq_fore_green),$(colour.escseq_back_red)
# 22  YELLOW_RED
style.escseq.22=$(colour.escseq_fore_yellow),$(colour.escseq_back_red)
# 23  BLUE_RED
style.escseq.23=$(colour.escseq_fore_blue),$(colour.escseq_back_red)
# 24  MAGENTA_RED
style.escseq.24=$(colour.escseq_fore_magenta),$(colour.escseq_back_red)
# 25  CYAN_RED
style.escseq.25=$(colour.escseq_fore_cyan),$(colour.escseq_back_red)
# 26  WHITE_RED
style.escseq.26=$(colour.escseq_fore_white),$(colour.escseq_back_red)
# 27  DEFAULT_GREEN
style.escseq.27=$(colour.escseq_fore_default),$(colour.escseq_back_green)
# 28  BLACK_GREEN
style.escseq.28=$(colour.escseq_fore_black),$(colour.escseq_back_green)
# 29  RED_GREEN
style.escseq.29=$(colour.escseq_fore_red),$(colour.escseq_back_green)
# 30  GREEN_GREEN
style.escseq.30=$(colour.escseq_fore_green),$(colour.escseq_back_green)

# 40  YELLOW_GREEN
style.escseq.40=$(colour.escseq_fore_yellow),$(colour.escseq_back_green)
# 41  BLUE_GREEN
style.escseq.41=$(colour.escseq_fore_blue),$(colour.escseq_back_green)
# 42  MAGENTA_GREEN
style.escseq.42=$(colour.escseq_fore_magenta),$(colour.escseq_back_green)
# 43  CYAN_GREEN
style.escseq.43=$(colour.escseq_fore_cyan),$(colour.escseq_back_green)
# 44  WHITE_GREEN
style.escseq.44=$(colour.escseq_fore_white),$(colour.escseq_back_green)
# 45  DEFAULT_YELLOW
style.escseq.45=$(colour.escseq_fore_default),$(colour.escseq_back_yellow)
# 46  BLACK_YELLOW
style.escseq.46=$(colour.escseq_fore_black),$(colour.escseq_back_yellow)
# 47  RED_YELLOW
style.escseq.47=$(colour.escseq_fore_red),$(colour.escseq_back_yellow)
# 48  GREEN_YELLOW
style.escseq.48=$(colour.escseq_fore_green),$(colour.escseq_back_yellow)
# 49  YELLOW_YELLOW
style.escseq.49=$(colour.escseq_fore_yellow),$(colour.escseq_back_yellow)
# 50  BLUE_YELLOW
style.escseq.50=$(colour.escseq_fore_blue),$(colour.escseq_back_yellow)
# 51  MAGENTA_YELLOW
style.escseq.51=$(colour.escseq_fore_magenta),$(colour.escseq_back_yellow)
# 52  CYAN_YELLOW
style.escseq.52=$(colour.escseq_fore_cyan),$(colour.escseq_back_yellow)
# 53  WHITE_YELLOW
style.escseq.53=$(colour.escseq_fore_white),$(colour.escseq_back_yellow)
# 54  DEFAULT_BLUE
style.escseq.54=$(colour.escseq_fore_default),$(colour.escseq_back_blue)
# 55  BLACK_BLUE
style.escseq.55=$(colour.escseq_fore_black),$(colour.escseq_back_blue)
# 56  RED_BLUE
style.escseq.56=$(colour.escseq_fore_red),$(colour.escseq_back_blue)
# 57  GREEN_BLUE
style.escseq.57=$(colour.escseq_fore_green),$(colour.escseq_back_blue)
# 58  YELLOW_BLUE
style.escseq.58=$(colour.escseq_fore_yellow),$(colour.escseq_back_blue)
# 59  BLUE_BLUE
style.escseq.59=$(colour.escseq_fore_blue),$(colour.escseq_back_blue)
# 60  MAGENTA_BLUE
style.escseq.60=$(colour.escseq_fore_magenta),$(colour.escseq_back_blue)
# 61  CYAN_BLUE
style.escseq.61=$(colour.escseq_fore_cyan),$(colour.escseq_back_blue)
# 62  WHITE_BLUE
style.escseq.62=$(colour.escseq_fore_white),$(colour.escseq_back_blue)
# 63  DEFAULT_MAGENTA
style.escseq.63=$(colour.escseq_fore_default),$(colour.escseq_back_magenta)
# 64  BLACK_MAGENTA
style.escseq.64=$(colour.escseq_fore_black),$(colour.escseq_back_magenta)
# 65  RED_MAGENTA
style.escseq.65=$(colour.escseq_fore_red),$(colour.escseq_back_magenta)
# 66  GREEN_MAGENTA
style.escseq.66=$(colour.escseq_fore_green),$(colour.escseq_back_magenta)
# 67  YELLOW_MAGENTA
style.escseq.67=$(colour.escseq_fore_yellow),$(colour.escseq_back_magenta)
# 68  BLUE_MAGENTA
style.escseq.68=$(colour.escseq_fore_blue),$(colour.escseq_back_magenta)
# 69  MAGENTA_MAGENTA
style.escseq.69=$(colour.escseq_fore_magenta),$(colour.escseq_back_magenta)
# 70  CYAN_MAGENTA
style.escseq.70=$(colour.escseq_fore_cyan),$(colour.escseq_back_magenta)
# 71  WHITE_MAGENTA
style.escseq.71=$(colour.escseq_fore_white),$(colour.escseq_back_magenta)
# 72  DEFAULT_CYAN
style.escseq.72=$(colour.escseq_fore_default),$(colour.escseq_back_cyan)
# 73  BLACK_CYAN
style.escseq.73=$(colour.escseq_fore_black),$(colour.escseq_back_cyan)
# 74  RED_CYAN
style.escseq.74=$(colour.escseq_fore_red),$(colour.escseq_back_cyan)
# 75  GREEN_CYAN
style.escseq.75=$(colour.escseq_fore_green),$(colour.escseq_back_cyan)
# 76  YELLOW_CYAN
style.escseq.76=$(colour.escseq_fore_yellow),$(colour.escseq_back_cyan)
# 77  BLUE_CYAN
style.escseq.77=$(colour.escseq_fore_blue),$(colour.escseq_back_cyan)
# 78  MAGENTA_CYAN
style.escseq.78=$(colour.escseq_fore_magenta),$(colour.escseq_back_cyan)
# 79  CYAN_CYAN
style.escseq.79=$(colour.escseq_fore_cyan),$(colour.escseq_back_cyan)
# 80  WHITE_CYAN
style.escseq.80=$(colour.escseq_fore_white),$(colour.escseq_back_cyan)
# 81  DEFAULT_WHITE
style.escseq.81=$(colour.escseq_fore_default),$(colour.escseq_back_white)
# 82  BLACK_WHITE
style.escseq.82=$(colour.escseq_fore_black),$(colour.escseq_back_white)
# 83  RED_WHITE
style.escseq.83=$(colour.escseq_fore_red),$(colour.escseq_back_white)
# 84  GREEN_WHITE
style.escseq.84=$(colour.escseq_fore_green),$(colour.escseq_back_white)
# 85  YELLOW_WHITE
style.escseq.85=$(colour.escseq_fore_yellow),$(colour.escseq_back_white)
# 86  BLUE_WHITE
style.escseq.86=$(colour.escseq_fore_blue),$(colour.escseq_back_white)
# 87  MAGENTA_WHITE
style.escseq.87=$(colour.escseq_fore_magenta),$(colour.escseq_back_white)
# 88  CYAN_WHITE
style.escseq.88=$(colour.escseq_fore_cyan),$(colour.escseq_back_white)
# 89  WHITE_WHITE
style.escseq.89=$(colour.escseq_fore_white),$(colour.escseq_back_white)

# 90  BOLD_DEFAULT
style.escseq.90=$(colour.escseq_fore_default),$(colour.escseq_back_default),bold
# 91  BOLD_BLACK_DEFAULT
style.escseq.91=$(colour.escseq_fore_black),$(colour.escseq_back_default),bold
# 92  BOLD_RED_DEFAULT
style.escseq.92=$(colour.escseq_fore_red),$(colour.escseq_back_default),bold
# 93  BOLD_GREEN_DEFAULT
style.escseq.93=$(colour.escseq_fore_green),$(colour.escseq_back_default),bold
# 94  BOLD_YELLOW_DEFAULT
style.escseq.94=$(colour.escseq_fore_yellow),$(colour.escseq_back_default),bold
# 95  BOLD_BLUE_DEFAULT
style.escseq.95=$(colour.escseq_fore_blue),$(colour.escseq_back_default),bold
# 96  BOLD_MAGENTA_DEFAULT
style.escseq.96=$(colour.escseq_fore_magenta),$(colour.escseq_back_default),bold
# 97  BOLD_CYAN_DEFAULT
style.escseq.97=$(colour.escseq_fore_cyan),$(colour.escseq_back_default),bold
# 98  BOLD_WHITE_DEFAULT
style.escseq.98=$(colour.escseq_fore_white),$(colour.escseq_back_default),bold
# 99  BOLD_DEFAULT_BLACK
style.escseq.99=$(colour.escseq_fore_default),$(colour.escseq_back_black),bold
# 100  BOLD_BLACK_BLACK
style.escseq.100=$(colour.escseq_fore_black),$(colour.escseq_back_black),bold
# 101  BOLD_RED_BLACK
style.escseq.101=$(colour.escseq_fore_red),$(colour.escseq_back_black),bold
# 102  BOLD_GREEN_BLACK
style.escseq.102=$(colour.escseq_fore_green),$(colour.escseq_back_black),bold
# 103  BOLD_YELLOW_BLACK
style.escseq.103=$(colour.escseq_fore_yellow),$(colour.escseq_back_black),bold
# 104  BOLD_BLUE_BLACK
style.escseq.104=$(colour.escseq_fore_blue),$(colour.escseq_back_black),bold
# 105  BOLD_MAGENTA_BLACK
style.escseq.105=$(colour.escseq_fore_magenta),$(colour.escseq_back_black),bold
# 106  BOLD_CYAN_BLACK
style.escseq.106=$(colour.escseq_fore_cyan),$(colour.escseq_back_black),bold
# 107  BOLD_WHITE_BLACK
style.escseq.107=$(colour.escseq_fore_white),$(colour.escseq_back_black),bold
# 108  BOLD_DEFAULT_RED
style.escseq.108=$(colour.escseq_fore_default),$(colour.escseq_back_red),bold
# 109  BOLD_BLACK_RED
style.escseq.109=$(colour.escseq_fore_black),$(colour.escseq_back_red),bold
# 110  BOLD_RED_RED
style.escseq.110=$(colour.escseq_fore_red),$(colour.escseq_back_red),bold
# 111  BOLD_GREEN_RED
style.escseq.111=$(colour.escseq_fore_green),$(colour.escseq_back_red),bold
# 112  BOLD_YELLOW_RED
style.escseq.112=$(colour.escseq_fore_yellow),$(colour.escseq_back_red),bold
# 113  BOLD_BLUE_RED
style.escseq.113=$(colour.escseq_fore_blue),$(colour.escseq_back_red),bold
# 114  BOLD_MAGENTA_RED
style.escseq.114=$(colour.escseq_fore_magenta),$(colour.escseq_back_red),bold
# 115  BOLD_CYAN_RED
style.escseq.115=$(colour.escseq_fore_cyan),$(colour.escseq_back_red),bold
# 116  BOLD_WHITE_RED
style.escseq.116=$(colour.escseq_fore_white),$(colour.escseq_back_red),bold
# 117  BOLD_DEFAULT_GREEN
style.escseq.117=$(colour.escseq_fore_default),$(colour.escseq_back_green),bold
# 118  BOLD_BLACK_GREEN
style.escseq.118=$(colour.escseq_fore_black),$(colour.escseq_back_green),bold
# 119  BOLD_RED_GREEN
style.escseq.119=$(colour.escseq_fore_red),$(colour.escseq_back_green),bold
# 120  BOLD_GREEN_GREEN
style.escseq.120=$(colour.escseq_fore_green),$(colour.escseq_back_green),bold
# 121  BOLD_YELLOW_GREEN
style.escseq.121=$(colour.escseq_fore_yellow),$(colour.escseq_back_green),bold
# 122  BOLD_BLUE_GREEN
style.escseq.122=$(colour.escseq_fore_blue),$(colour.escseq_back_green),bold
# 123  BOLD_MAGENTA_GREEN
style.escseq.123=$(colour.escseq_fore_magenta),$(colour.escseq_back_green),bold
# 124  BOLD_CYAN_GREEN
style.escseq.124=$(colour.escseq_fore_cyan),$(colour.escseq_back_green),bold
# 125  BOLD_WHITE_GREEN
style.escseq.125=$(colour.escseq_fore_white),$(colour.escseq_back_green),bold
# 126  BOLD_DEFAULT_YELLOW
style.escseq.126=$(colour.escseq_fore_default),$(colour.escseq_back_yellow),bold
# 127  BOLD_BLACK_YELLOW
style.escseq.127=$(colour.escseq_fore_black),$(colour.escseq_back_yellow),bold
# 128  BOLD_RED_YELLOW
style.escseq.128=$(colour.escseq_fore_red),$(colour.escseq_back_yellow),bold
# 129  BOLD_GREEN_YELLOW
style.escseq.129=$(colour.escseq_fore_green),$(colour.escseq_back_yellow),bold
# 130  BOLD_YELLOW_YELLOW
style.escseq.130=$(colour.escseq_fore_yellow),$(colour.escseq_back_yellow),bold
# 131  BOLD_BLUE_YELLOW
style.escseq.131=$(colour.escseq_fore_blue),$(colour.escseq_back_yellow),bold
# 132  BOLD_MAGENTA_YELLOW
style.escseq.132=$(colour.escseq_fore_magenta),$(colour.escseq_back_yellow),bold
# 133  BOLD_CYAN_YELLOW
style.escseq.133=$(colour.escseq_fore_cyan),$(colour.escseq_back_yellow),bold
# 134  BOLD_WHITE_YELLOW
style.escseq.134=$(colour.escseq_fore_white),$(colour.escseq_back_yellow),bold
# 135  BOLD_DEFAULT_BLUE
style.escseq.135=$(colour.escseq_fore_default),$(colour.escseq_back_blue),bold
# 136  BOLD_BLACK_BLUE
style.escseq.136=$(colour.escseq_fore_black),$(colour.escseq_back_blue),bold
# 137  BOLD_RED_BLUE
style.escseq.137=$(colour.escseq_fore_red),$(colour.escseq_back_blue),bold
# 138  BOLD_GREEN_BLUE
style.escseq.138=$(colour.escseq_fore_green),$(colour.escseq_back_blue),bold
# 139  BOLD_YELLOW_BLUE
style.escseq.139=$(colour.escseq_fore_yellow),$(colour.escseq_back_blue),bold
# 140  BOLD_BLUE_BLUE
style.escseq.140=$(colour.escseq_fore_blue),$(colour.escseq_back_blue),bold
# 141  BOLD_MAGENTA_BLUE
style.escseq.141=$(colour.escseq_fore_magenta),$(colour.escseq_back_blue),bold
# 142  BOLD_CYAN_BLUE
style.escseq.142=$(colour.escseq_fore_cyan),$(colour.escseq_back_blue),bold
# 143  BOLD_WHITE_BLUE
style.escseq.143=$(colour.escseq_fore_white),$(colour.escseq_back_blue),bold
# 144  BOLD_DEFAULT_MAGENTA
style.escseq.144=$(colour.escseq_fore_default),$(colour.escseq_back_magenta),bold
# 145  BOLD_BLACK_MAGENTA
style.escseq.145=$(colour.escseq_fore_black),$(colour.escseq_back_magenta),bold
# 146  BOLD_RED_MAGENTA
style.escseq.146=$(colour.escseq_fore_red),$(colour.escseq_back_magenta),bold
# 147  BOLD_GREEN_MAGENTA
style.escseq.147=$(colour.escseq_fore_green),$(colour.escseq_back_magenta),bold
# 148  BOLD_YELLOW_MAGENTA
style.escseq.148=$(colour.escseq_fore_yellow),$(colour.escseq_back_magenta),bold
# 149  BOLD_BLUE_MAGENTA
style.escseq.149=$(colour.escseq_fore_blue),$(colour.escseq_back_magenta),bold
# 150  BOLD_MAGENTA_MAGENTA
style.escseq.150=$(colour.escseq_fore_magenta),$(colour.escseq_back_magenta),bold
# 151  BOLD_CYAN_MAGENTA
style.escseq.151=$(colour.escseq_fore_cyan),$(colour.escseq_back_magenta),bold
# 152  BOLD_WHITE_MAGENTA
style.escseq.152=$(colour.escseq_fore_white),$(colour.escseq_back_magenta),bold
# 153  BOLD_DEFAULT_CYAN
style.escseq.153=$(colour.escseq_fore_default),$(colour.escseq_back_cyan),bold
# 154  BOLD_BLACK_CYAN
style.escseq.154=$(colour.escseq_fore_black),$(colour.escseq_back_cyan),bold
# 155  BOLD_RED_CYAN
style.escseq.155=$(colour.escseq_fore_red),$(colour.escseq_back_cyan),bold
# 156  BOLD_GREEN_CYAN
style.escseq.156=$(colour.escseq_fore_green),$(colour.escseq_back_cyan),bold
# 157  BOLD_YELLOW_CYAN
style.escseq.157=$(colour.escseq_fore_yellow),$(colour.escseq_back_cyan),bold
# 158  BOLD_BLUE_CYAN
style.escseq.158=$(colour.escseq_fore_blue),$(colour.escseq_back_cyan),bold
# 159  BOLD_MAGENTA_CYAN
style.escseq.159=$(colour.escseq_fore_magenta),$(colour.escseq_back_cyan),bold
# 160  BOLD_CYAN_CYAN
style.escseq.160=$(colour.escseq_fore_cyan),$(colour.escseq_back_cyan),bold
# 161  BOLD_WHITE_CYAN
style.escseq.161=$(colour.escseq_fore_white),$(colour.escseq_back_cyan),bold
# 162  BOLD_DEFAULT_WHITE
style.escseq.162=$(colour.escseq_fore_default),$(colour.escseq_back_white),bold
# 163  BOLD_BLACK_WHITE
style.escseq.163=$(colour.escseq_fore_black),$(colour.escseq_back_white),bold
# 164  BOLD_RED_WHITE
style.escseq.164=$(colour.escseq_fore_red),$(colour.escseq_back_white),bold
# 165  BOLD_GREEN_WHITE
style.escseq.165=$(colour.escseq_fore_green),$(colour.escseq_back_white),bold
# 166  BOLD_YELLOW_WHITE
style.escseq.166=$(colour.escseq_fore_yellow),$(colour.escseq_back_white),bold
# 167  BOLD_BLUE_WHITE
style.escseq.167=$(colour.escseq_fore_blue),$(colour.escseq_back_white),bold
# 168  BOLD_MAGENTA_WHITE
style.escseq.168=$(colour.escseq_fore_magenta),$(colour.escseq_back_white),bold
# 169  BOLD_CYAN_WHITE
style.escseq.169=$(colour.escseq_fore_cyan),$(colour.escseq_back_white),bold
# 170  BOLD_WHITE_WHITE
style.escseq.170=$(colour.escseq_fore_white),$(colour.escseq_back_white),bold

# 171  IDENTIFIER
style.escseq.171=back:#EEFFEE
# 172  UNKNOWN
style.escseq.172=back:#FFEEEE
