/* This file was generated by syncqt. */
#ifndef QT_QTDESIGNER_VERSION_H
#define QT_QTDESIGNER_VERSION_H

#define QTDESIGNER_VERSION_STR "5.2.1"

#define QTDESIGNER_VERSION 0x050201

#endif // QT_QTDESIGNER_VERSION_H
