/* This file was generated by syncqt. */
#ifndef QT_QTGUI_VERSION_H
#define QT_QTGUI_VERSION_H

#define QTGUI_VERSION_STR "5.2.1"

#define QTGUI_VERSION 0x050201

#endif // QT_QTGUI_VERSION_H
