/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "5.2.1"

#define QTSENSORS_VERSION 0x050201

#endif // QT_QTSENSORS_VERSION_H
