/* This file was generated by syncqt. */
#ifndef QT_QTSVG_VERSION_H
#define QT_QTSVG_VERSION_H

#define QTSVG_VERSION_STR "5.2.1"

#define QTSVG_VERSION 0x050201

#endif // QT_QTSVG_VERSION_H
